import { UrlShortenerForm } from "@/components/url-shortener-form";
import { isDatabaseConfigured } from "@/lib/env";

const features = [
  {
    title: "Anonymous by default",
    description: "No login flow, no account setup, no clutter. Paste a link and get a short URL back."
  },
  {
    title: "Random, clean short codes",
    description: "Each link gets a compact Base62 code generated by the server with collision checks."
  },
  {
    title: "Managed Postgres ready",
    description: "Built to run cleanly on Vercel with Prisma and a managed PostgreSQL database like Neon."
  }
];

export default function HomePage() {
  const databaseReady = isDatabaseConfigured();

  return (
    <main className="relative overflow-hidden px-6 py-8 sm:px-10 lg:px-12">
      <div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl flex-col justify-between">
        <header className="flex items-center justify-between py-4">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.35em] text-sea">
              Flashlink
            </p>
            <p className="mt-2 text-sm text-ink/60">
              Anonymous random-only URL shortener
            </p>
          </div>
          <div className="rounded-full border border-ink/10 bg-white/70 px-4 py-2 text-xs font-medium text-ink/70 backdrop-blur">
            Next.js • TypeScript • Prisma
          </div>
        </header>

        <section className="grid items-center gap-10 py-12 lg:grid-cols-[1.1fr_0.9fr] lg:py-20">
          <div>
            <p className="inline-flex rounded-full border border-sea/20 bg-white/70 px-4 py-2 text-xs font-semibold uppercase tracking-[0.28em] text-sea backdrop-blur">
              Fast links without the baggage
            </p>
            <h1 className="mt-6 max-w-3xl text-5xl font-semibold tracking-tight text-ink sm:text-6xl">
              Shorten any link into a crisp shareable URL.
            </h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-ink/70">
              Flashlink gives you one job and does it well: take a long URL, generate a random short code,
              and redirect fast. No aliases, no account system, no unnecessary friction.
            </p>

            <div className="mt-10 grid gap-4 sm:grid-cols-3">
              {features.map((feature) => (
                <div
                  key={feature.title}
                  className="rounded-[28px] border border-black/5 bg-white/85 p-5 shadow-card backdrop-blur"
                >
                  <h2 className="text-base font-semibold text-ink">{feature.title}</h2>
                  <p className="mt-2 text-sm leading-6 text-ink/65">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-[36px] border border-black/5 bg-white/90 p-6 shadow-card backdrop-blur sm:p-8">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold uppercase tracking-[0.28em] text-sea">
                  Create link
                </p>
                <p className="mt-2 text-sm text-ink/60">
                  Paste a destination URL and Flashlink will generate a random short code.
                </p>
              </div>
              <div className="rounded-full bg-sand px-3 py-1 text-xs font-semibold text-ink/70">
                Random only
              </div>
            </div>
            {!databaseReady ? (
              <div className="mt-6 rounded-[24px] border border-amber-200 bg-amber-50 px-4 py-4 text-sm leading-6 text-amber-900">
                <code className="rounded bg-white/80 px-1.5 py-0.5 text-xs font-semibold">DATABASE_URL</code> is
                not configured yet, so the app is in setup mode. Add your managed Postgres connection string and{" "}
                <code className="rounded bg-white/80 px-1.5 py-0.5 text-xs font-semibold">
                  NEXT_PUBLIC_APP_URL
                </code>
                , then run{" "}
                <code className="rounded bg-white/80 px-1.5 py-0.5 text-xs font-semibold">npm run db:push</code>.
              </div>
            ) : null}
            <div className="mt-8">
              <UrlShortenerForm disabled={!databaseReady} />
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}
